[project]
name = "game-meta"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.game_meta]
path = "contracts/game_meta.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
